LiveFraction stops at Fraction
so for example typing `d/dx d/dx` or `1/2 3/4` does what you'd expect.

Exception: LiveFraction *immediately after* a Fraction doesn't make an
empty numerator, it puts the previous fraction in the numerator, so for
example `1/2 /3` does what you expect. Ditto with TextBlocks (so typing
`$Fractions such as $1/2` and `$distance$/2` each do what you expect).